noyel/kdo/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('noyel.kdo.views',
    url(r'^landing/$', 'landing', name='kdo-landing'),
    
    url(r'^api/search/giftee/$', 'search_giftee', name='kdo-search-giftee'),
    url(r'^api/search/friend/$', 'search_friend', name='kdo-search-friend'),
)

urlpatterns.extend(patterns('noyel.kdo.views.comment',
    url(r'^presents/(?P<pk>\d+)/comments/create/$', 'create', name='kdo-comment-create'),
    
    url(r'^comments/(?P<pk>\d+)/update/$', 'update', name='kdo-comment-update'),
    url(r'^comments/(?P<pk>\d+)/delete/$', 'delete', name='kdo-comment-delete'),

))

urlpatterns.extend(patterns('noyel.kdo.views.present',
    url(r'^presents/$', 'base_list', name='kdo-present-list'),
    url(r'^presents/create/$', 'create', name='kdo-present-create'),
    url(r'^presents/(?P<pk>\d+)/$', 'detail', name='kdo-present-detail'),
    url(r'^presents/(?P<pk>\d+)/update/$', 'update', name='kdo-present-update'),
    url(r'^presents/(?P<pk>\d+)/delete/$', 'delete', name='kdo-present-delete'),
    url(r'^presents/(?P<pk>\d+)/purchase/$', 'purchase', name='kdo-present-purchase'),
    
    
    url(r'^presents/for/(?P<giftee>.+)/$', 'list_for_giftee', name='kdo-present-list-for-giftee'),
    url(r'^presents/create/for/(?P<giftee>.+)/$', 'create_for_giftee', name='kdo-present-create-for-giftee'),
    
    
    url(r'^presents/(?P<pk>\d+)/participants/(?P<user_pk>\d+)/remove/$', 'remove_participant', name='kdo-present-remove-participant'),

))

urlpatterns.extend(patterns('noyel.kdo.views.invitation',
    url(r'^presents/(?P<pk>\d+)/participants/invite/$', 'invite_participant', name='kdo-present-invite-participant'),

    url(r'^invitations/$', 'list', name='kdo-invitation-list'),
    url(r'^invitations/redeem/$', 'redeem', name='kdo-redeem-invitation'),
    url(r'^invitations/(?P<token>\w+)/redeem/$', 'redeem_with_token', name='kdo-redeem-invitation-with-token'),
    url(r'^invitations/(?P<token>\w+)/delete/$', 'delete', name='kdo-invitation-delete'),
    url(r'^invitations/(?P<token>\w+)/re-send/$', 're_send', name='kdo-invitation-re-send'),
))

noyel/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.shortcuts import redirect as _redirect
from noyel.kdo.urls import urlpatterns as kdo_patterns
from noyel.account.urls import urlpatterns as account_patterns

admin.autodiscover()

def redirect(to, *args, **kwargs):
    """Return a view (callable) that can be used as the second parameter to the
    url function.
    That view will permanently redirect to the given URL.
    The given parameters will be passed as-is to the shortcuts.redirect function.
    
    """
    def view(request):
        return _redirect(to, *args, permanent=True, **kwargs)
    return view

urlpatterns = patterns('',
    url(r'^$', redirect('kdo-welcome')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

urlpatterns.extend(kdo_patterns)
urlpatterns.extend(account_patterns)

noyel/kdo/models.py
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _, pgettext_lazy
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.functional import curry
from django.contrib.sites.models import get_current_site

from noyel.kdo.emails import InvitationEmail


class Present(models.Model):
    class STATUS(object):
        REJECTED = 0
        SUGGESTED = 1
        ACCEPTED = 2
        BOUGHT = 3
        ARCHIVED = 10
        
        choices = [
            (REJECTED, _("rejected")),
            (SUGGESTED, _("suggested")),
            (ACCEPTED, _("accepted")),
            (BOUGHT, _("bought")),
            (ARCHIVED, _("archived")),
        ]
    title = models.CharField(_("title"), max_length=50)
    giftee = models.CharField(_("giftee"), max_length=100)
    description = models.TextField(_("description"), blank=True)
    link = models.URLField(_("link"), blank=True)
    price = models.DecimalField(_("price"), max_digits=6, decimal_places=2,
                blank=True, null=True)
    status = models.PositiveIntegerField(_("status"), choices=STATUS.choices,
                default=STATUS.SUGGESTED)
    bought_by = models.ForeignKey('auth.User', verbose_name=_("bought by"),
                                  blank=True, null=True,
                                  related_name='purchased_set')
    
    created_on = models.DateTimeField(_("added on"), auto_now_add=True)
    updated_on = models.DateTimeField(_("updated on"), auto_now=True)
    
    class Meta:
        verbose_name = _("present")
        verbose_name_plural = _("presents")
    
    def __unicode__(self):
        return self.title
    
    def matching_giftee(self, user=None):
        """Return a queryset of presents that have the same giftee as this one.
        If a user is passed, restrict to presents for which the user is listed
        in the participants.
        
        """
        qs = self.__class__.objects.filter(giftee__iexact=self.giftee).exclude(pk=self.pk)
        if user is not None:
            qs = qs.filter(participants__user=user)
        return qs
    
    def get_new_friends_for_user(self, user):
        """Return a queryset of User objects that have participated in a present
        with the given user, but that are not participating to the current one.
        
        """
        return User.objects.exclude(present=self)\
                           .filter(present__participants__user=user)


class Comment(models.Model):
    present = models.ForeignKey('kdo.Present', verbose_name=_('present'))
    author = models.ForeignKey('auth.User', verbose_name=_("author"))
    text = models.TextField(_("text"))
    posted_on = models.DateTimeField(_("posted on"), auto_now_add=True)
    
    def __unicode__(self):
        cutoff = 20
        if len(self.text) > cutoff:
            return u"%s..." % self.text[:cutoff]
        else:
            return self.text
    
    class Meta:
        verbose_name = _("comment")
        verbose_name_plural = _("comments")
        ordering = ['-posted_on']


class InvitationManager(models.Manager):
    def for_user(self, user):
        """Return invitations for the given user."""
        q = Invitation.Q_for_user(user)
        return self.get_query_set().filter(q)


class Invitation(models.Model):
    TOKEN_SIZE = 16
    token = models.CharField(_("token"), max_length=TOKEN_SIZE, primary_key=True, default=curry(get_random_string, TOKEN_SIZE))
    present = models.ForeignKey('kdo.Present', verbose_name=_("present"))
    sent_by = models.ForeignKey('auth.User', verbose_name=pgettext_lazy("invitation", "sent by"))
    sent_to = models.EmailField(pgettext_lazy("invitation", "sent to"))
    sent_on = models.DateTimeField(pgettext_lazy("invitation", "sent on"), auto_now_add=True)
    
    objects = InvitationManager()
    
    def __unicode__(self):
        return self.sent_to
    
    class Meta:
        verbose_name = _("invitation")
        verbose_name_plural = _("invitations")
        unique_together = ('present', 'sent_to')
    
    def redeem(self, user):
        Participant.objects.create(user=user, present=self.present)
        self.delete() # XXX good idea?
        return self.present
    
    @classmethod
    def Q_for_user(cls, user):
        emails = user.emails.filter(verified=True)\
                            .values_list('email', flat=True)
        return models.Q(sent_to__in=emails)
    
    def get_message(self, request):
        """Return a rendered InvitationEmail message with the given request."""
        site = get_current_site(request)
        return InvitationEmail().render({
            'site': site,
            'invitation': self,
            })
    
    def send_email(self, request):
        message = self.get_message(request)
        return message.send()


class Participant(models.Model):
    present = models.ForeignKey(Present, related_name='participants')
    user = models.ForeignKey('auth.User')
    
    class Meta:
        verbose_name = _("participant")
        verbose_name_plural = _("participants")
        unique_together = ('present', 'user')

noyel/kdo/views/comment.py
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.views import generic

from noyel.kdo.forms import CommentCreateForm, CommentUpdateForm
from noyel.kdo.mixins import LoginRequiredMixin, UserQuerysetMixin
from noyel.kdo.models import Present, Comment

from toolbox.messages import FormMessageMixin, DeleteMessageMixin
from toolbox.next import NextMixin


class CreateView(LoginRequiredMixin, NextMixin, FormMessageMixin, generic.CreateView):
    """Add a comment to the given present."""
    model = Comment
    form_class = CommentCreateForm
    form_valid_message = _("The comment has been created successfully.")
    
    @property
    def default_next_url(self):
        return reverse('kdo-present-detail', args=[self.present.pk])
    
    def get_form_kwargs(self):
        """Add the current user to the form's kwargs."""
        kwargs = super(CreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['present'] = self.present
        return kwargs
    
    def dispatch(self, request, *args, **kwargs):
        self.present = get_object_or_404(Present, pk=kwargs['pk'],
                                         participants__user=request.user)
        return super(CreateView, self).dispatch(request, *args, **kwargs)

create = CreateView.as_view()


class UpdateView(LoginRequiredMixin, UserQuerysetMixin, NextMixin, FormMessageMixin, generic.UpdateView):
    """Update the given comment. Only available if the user if the comment's
    author.
    
    """
    model = Comment
    form_class = CommentUpdateForm
    user_field_name = 'author'
    form_valid_message = _("The comment has been updated successfully.")
    
    @property
    def default_next_url(self):
        return reverse('kdo-present-detail', args=[self.object.present.pk])

update = UpdateView.as_view()


class DeleteView(LoginRequiredMixin, UserQuerysetMixin, NextMixin, DeleteMessageMixin, generic.DeleteView):
    """Delete the given comment, but only if the current user is the comments's
    author.
    
    """
    model = Comment
    user_field_name = 'author'
    delete_message = _("The comment has been deleted successfully.")
    
    @property
    def default_next_url(self):
        return reverse('kdo-present-detail', args=[self.object.present.pk])

delete = DeleteView.as_view()

noyel/kdo/views/invitation.py
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now

from django.views import generic
from django.views.generic.detail import SingleObjectMixin

from noyel.kdo import forms as kdo_forms
from noyel.kdo.mixins import LoginRequiredMixin, UserQuerysetMixin
from noyel.kdo.models import Present, Invitation

from toolbox.messages import MessageMixin, FormMessageMixin, DeleteMessageMixin
from toolbox.next import NextMixin


class InviteParticipantView(LoginRequiredMixin, NextMixin, MessageMixin, generic.FormView):
    """Invite a participant to a present.
    If a username is given and that the corresponding user is a friend of the
    current one, then it is immediately added to the present's participants list.
    
    If an email is given, then a message is sent to that address with a unique
    link that will allow the user who receives it to be added to the present's
    participants list.
    
    """
    template_name = 'kdo/invite_participant.html'
    form_class = kdo_forms.PresentInvitationForm
    
    @property
    def default_next_url(self):
        return reverse('kdo-present-detail', args=[self.present.pk])
    
    def dispatch(self, request, *args, **kwargs):
        self.present = get_object_or_404(Present, pk=kwargs['pk'],
                                         participants__user=request.user)
        return super(InviteParticipantView, self).dispatch(request, *args,
                                                           **kwargs)
    
    def get_form_kwargs(self):
        kwargs = super(InviteParticipantView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['present'] = self.present
        return kwargs
    
    def form_valid(self, form):
        """If a user was given, then add it to the participants list right away.
        
        If an email was given and it corresponds to a friend, then add it too.
        
        Otherwise, send an invitation email to the given address.
        
        """
        users, email = form.cleaned_data['friends'], form.cleaned_data['email']
        if users:
            for user in users:
                try:
                    self.present.participants.create(user=user,
                                                     present=self.present)
                except IntegrityError: # already participating
                    pass
            msg = _("The users have been added to the present's participants "
                    "successfully.")
            self.messages.success(msg)
            return super(InviteParticipantView, self).form_valid(form)

        try:
            invitation = form.save_invitation()
        except IntegrityError: # invitation already sent
            msg = _("The user \"%(email_address)s\" has already been "
                    "invited to this present.")
            self.messages.error(msg % {
                'email_address': form.cleaned_data['user'],
                })
            return self.form_invalid(form)
        
        invitation.send_email(self.request)
        msg = _("An email has been sent to the user inviting them to "
                "participate to this present.")
        self.messages.success(msg)
        return super(InviteParticipantView, self).form_valid(form)

invite_participant = InviteParticipantView.as_view()


class ReSendView(LoginRequiredMixin, UserQuerysetMixin, MessageMixin, SingleObjectMixin, NextMixin, generic.View):
    """Re-send the invitation email and update its sent_on attribute."""
    model = Invitation
    pk_url_kwarg = 'token'
    user_field_name = 'present__participants__user'
    
    @property
    def default_next_url(self):
        return reverse('kdo-present-detail', args=[self.invitation.present_id])
    
    def post(self, request, *args, **kwargs):
        self.invitation = self.get_object()
        self.invitation.send_email(self.request)
        self.invitation.sent_on = now()
        self.invitation.save()
        msg = _("Invitation re-sent successfully.")
        self.messages.success(msg)
        return self.redirect()

re_send = ReSendView.as_view()


class RedeemView(LoginRequiredMixin, FormMessageMixin, generic.FormView):
    """Prompt for a token then redeem the corresponding invitation."""
    template_name = 'kdo/redeem_invitation.html'
    form_class = kdo_forms.RedeemInvitationForm
    form_valid_message = _("The invitation has been redeemed successfully.")
    
    def get_success_url(self):
        return reverse('kdo-present-detail', args=(self.present.pk,))
    
    def get_form_kwargs(self):
        kwargs = super(RedeemView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def form_valid(self, form):
        self.present = form.save()
        return super(RedeemView, self).form_valid(form)

redeem = RedeemView.as_view()


class RedeemWithTokenView(RedeemView):
    """Redeem the invitation correponding to the token given in the URL."""
    def get_initial(self):
        return self.kwargs

redeem_with_token = RedeemWithTokenView.as_view()


class ListView(LoginRequiredMixin, generic.ListView):
    """List pending invitations for the current user (ie those sent to the
    user's registered email address).
    
    """
    template_name = 'kdo/invitation_list.html'
    model = Invitation
    
    def get_queryset(self):
        base = super(ListView, self).get_queryset()
        base = base.filter(Invitation.Q_for_user(self.request.user))
        return base.select_related('present', 'sent_by').order_by('sent_on')

list = ListView.as_view()


class DeleteView(LoginRequiredMixin, UserQuerysetMixin, DeleteMessageMixin, NextMixin, generic.DeleteView):
    """"Delete an invitation. Only accessible to participants of the
    invitations's present.
    
    """
    template_name = 'kdo/invitation_delete.html'
    model = Invitation
    user_field_name = 'present__participants__user'
    pk_url_kwarg = 'token'
    
    @property
    def default_next_url(self):
        return reverse('kdo-present-detail', args=(self.present.pk,))

delete = DeleteView.as_view()

noyel/kdo/templates/kdo/comment_confirm_delete.html
{% extends 'basedelete.html' %}

noyel/kdo/templates/kdo/comment_form.html
{% extends 'baseform_icon.html' %}

{% block form_submit_icon %}comment{% endblock %}

noyel/kdo/templates/kdo/invitation_delete.html
{% extends 'basedelete.html' %}

noyel/kdo/templates/kdo/invitation_list.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'List of invitations' %}{% endblock %}

{% block content %}
<h1>{% trans 'List of invitations' %}</h1>
<table class="table table-striped table-hover">
    <thead><tr>
        <th>{% trans 'sent by'|capfirst context 'invitation' %}</th>
        <th>{% trans 'sent on'|capfirst context 'invitation' %}</th>
        <th>{% trans 'present'|capfirst %}</th>
        <th>{% trans 'giftee'|capfirst %}</th>
        <th>{% trans 'actions'|capfirst %}</th>
    </tr></thead>
    <tbody>
    {% for invitation in object_list %}
        <tr>
            <td>{{ invitation.sent_by.first_name|default:invitation.sent_by.username }}</td>
            <td>{{ invitation.sent_on|date }}</td>
            <td>{{ invitation.present.title }}</td>
            <td>{{ invitation.present.giftee }}</td>
            <td>
                <form action="{% url 'kdo-redeem-invitation' %}"
                      method="post">
                <button type="submit" class="btn">
                    <i class="icon-ok"></i>
                    {% trans 'redeem'|capfirst %}
                </button>
                <input type="hidden" name="token" value="{{ invitation.token }}">
                <input type="hidden" name="next" value="{{ request.get_full_path }}">
                {% csrf_token %}
                </form>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

noyel/kdo/templates/kdo/invite_participant.html
{% extends 'baseform_icon.html' %}

{% load i18n %}

{% block title %}{% trans 'Invite' %}{% endblock %}

{% block form_class %}{{ block.super }} invite{% endblock %}

{% block form_submit_text %}{% trans 'Invite' %}{% endblock %}

{% block form_submit_icon %}envelope{% endblock %}

{% block form_fields %}
{% if form.friends.field.queryset %}
    {% include 'snippets/field.html' with field=form.friends %}
{% endif %}
    {% include 'snippets/field.html' with field=form.email %}
{% endblock %}

noyel/kdo/templates/kdo/landing.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Landing' %}{% endblock %}

{% block content %}
{% if latest_presents %}
<h2>{% trans 'Latest presents' %}</h2>
<ul class="unstyled">
{% for present in latest_presents %}
    <li>
        <a href="{% url 'kdo-present-detail' present.pk %}">{{ present.title }}</a>
        {% url 'kdo-present-list-for-giftee' present.giftee as giftee_url %}
        {% blocktrans with giftee=present.giftee %}for <a href="{{ giftee_url }}">{{ giftee }}</a>{% endblocktrans %}
    </li>
{% endfor %}
</ul>
<h2>{% trans 'Latest comments' %}</h2>
<ul class="unstyled">
{% for comment in latest_comments %}
    <li>
        <blockquote>
            {{ comment.text|linebreaks }}
            <small>
            <span class="user" title="{{ comment.author.username }}">
                {{ comment.author.first_name }}
            </span>
            {% trans 'for present' %}
            <cite>
                <a href="{% url 'kdo-present-detail' comment.present.pk %}#comments">
                    {{ comment.present.title }}
                </a>
            </cite>
            {% blocktrans with date=comment.posted_on|date time=comment.posted_on|time %}on {{ date }} at {{ time }}{% endblocktrans %}
            </small>
        </blockquote>
    </li>
{% endfor %}
</ul>
{% else %}{# No presents in the list. The user is probably new #}
<h1>{% trans 'Are you new here?' %}</h1>
{% url 'kdo-present-create' as new_present_url %}
{% blocktrans %}It seems that you're not participating in any present.
Try <a href="{{ new_present_url }}">creating one</a> or ask your friends to add
you to an existing one.{% endblocktrans %}
{% endif %}
{% endblock %}

noyel/kdo/templates/kdo/present_confirm_delete.html
{% extends 'basedelete.html' %}

noyel/kdo/templates/kdo/present_create.html
{% extends 'baseform_icon.html' %}

{% load i18n %}

{% block title %}{% trans 'Add a present' %}{% endblock %}

{% block form_title %}{% trans 'Add a present' %}{% endblock %}

{% block form_submit_icon %}gift{% endblock %}

noyel/kdo/templates/kdo/present_detail.html
{% extends 'base.html' %}

{% load i18n kdo %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}


<div class="btn-group pull-right">
    {% if not object.bought_by %}
    <a class="btn btn-success"
       href="{% url 'kdo-present-purchase' object.pk %}?next={{ request.get_full_path|urlencode }}"
       title="{% trans 'I bought this present' %}">
        <i class="icon-shopping-cart icon-white"></i>
    </a>
    {% endif %}
    {% if not object.bought_by or object.bought_by == user %}
    <a class="btn btn-primary"
       href="{% url 'kdo-present-update' object.pk %}?next={{ request.get_full_path|urlencode }}"
       title="{% trans 'Update' %}">
        <i class="icon-pencil icon-white"></i>
    </a>
    {% endif %}
    {% if not object.bought_by %}
    <a class="btn btn-danger"
       href="{% url 'kdo-present-delete' object.pk %}"
       title="{% trans 'Delete' %}">
        <i class="icon-trash icon-white"></i>
    </a>
    {% endif %}
</div>

<h1>{{ object.title }}
{% if object.bought_by %}
<span class="bought-by" title="{{ object.bought_by.username }}">
<i class="icon-shopping-cart"></i>
</span>
{% endif %}
</h1>
<dl class="dl-horizontal">
    <dt>{% trans 'giftee'|capfirst %}</dt>
    <dd>
    {% with matching=present|count_matching_giftee:user %}
        {% if matching %}
            <a href="{% url 'kdo-present-list-for-giftee' object.giftee %}"
               title="{% blocktrans count matching=matching %}{{ matching }} other{% plural %} {{ matching }} others{% endblocktrans %}">
        {% endif %}
        
        {{ object.giftee }}
        
        {% if matching %}
        </a>
        {% endif %}
    {% endwith %}
    </dd>
    
    {% if object.description %}
    <dt>{% trans 'description'|capfirst %}</dt>
    <dd>{{ object.description|linebreaks }}</dd>
    {% endif %}
    
    {% if object.price %}
    <dt>{% trans 'price'|capfirst %}</dt>
    <dd>{{ object.price }}&nbsp;€</dd>
    {% endif %}
    
    {% if object.link %}
    <dt>{% trans 'link'|capfirst %}</dt>
    <dd><a href="{{ object.link }}">{{ object.link|netloc }}</a></dd>
    {% endif %}
    
    <dt>{% trans 'created on'|capfirst %}</dt>
    <dd>{{ object.created_on|date }}</dd>
    
    {% if object.created_on != object.updated_on %}
    <dt>{% trans 'updated on'|capfirst %}</dt>
    <dd>{{ object.updated_on|date }}</dd>
    {% endif %}
    
    {% if object.bought_by %}
    <dt>{% trans 'bought by'|capfirst %}</dt>
    <dd>
        {% if object.bought_by == user %}{% trans 'you'|capfirst %}
        {% else %}{{ object.bought_by.username }}
        {% endif %}
    </dd>
    {% endif %}
    
    <dt>{% trans 'participants'|capfirst %}</dt>
    <dd><ul class="unstyled inline">
        {% for participant in object.participants.all %}
            <li>
                <span class="label label-info">
                {{ participant.user.username }}
                {% if participant.user != user and participant.user != object.bought_by %}
                    <form action="{% url 'kdo-present-remove-participant' object.pk participant.user.pk %}"
                          method="post">
                        <button title="{% trans 'Remove' %}">
                            <i class="icon-trash"></i>
                        </button>
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        {% csrf_token %}
                    </form>
                {% elif participant.user == object.bought_by %}
                    <i class="icon-shopping-cart"></i>
                {% else %}
                    <i class="icon-heart"></i>
                {% endif %}
                </span>
            </li>
        {% endfor %}
        <li>
            <span class="label label-info">
                <a href="{% url 'kdo-present-invite-participant' object.pk %}?next={{ request.get_full_path|urlencode }}"
                   title="{% trans 'Invite a participant' %}">
                    <i class="icon-plus icon-white"></i>
                </a>
            </span>
        </li>
    </ul></dd>
    
    {% with pending=object.invitation_set.all %}
    {% if pending %}
        <dt>{% trans 'invitations'|capfirst %}</dt>
        <dd>
            <ul class="unstyled inline">
            {% for invitation in pending %}
                <li>
                    <span class="label">
                        <span title="{% blocktrans with since=invitation.sent_on|timesince %}{{ since }} ago{% endblocktrans %}">
                            {{ invitation.sent_to }}
                        </span>
                        <form action="{% url 'kdo-invitation-re-send' invitation.token %}"
                              method="post">
                            <button class="submit"
                                    title="{% trans 'Re-send this invitation' %}">
                                <i class="icon-refresh"></i>
                            </button>
                            <input type="hidden" name="next" value="{{ request.get_full_path }}">
                            {% csrf_token %}
                        </form>
                        <a href="{% url 'kdo-invitation-delete' invitation.token %}?next={{ request.get_full_path|urlencode }}"
                           title="{% trans 'delete'|capfirst %}">
                            <i class="icon-trash"></i>
                        </a>
                    </span>
                </li>
            {% endfor %}
            </ul>
        </dd>
    {% endif %}
    {% endwith %}
</ul>

<hr />
<h2>{% trans 'Comments' %}</h2>
<ul class="unstyled" id="comments">
{% for comment in object.comment_set.all %}
    <li>
        <blockquote>
            {{ comment.text|linebreaks|urlize }}
            <small>
            <span class="user" title="{{ comment.author.username }}">
                {{ comment.author.first_name }}
            </span>
            {% blocktrans with date=comment.posted_on|date time=comment.posted_on|time %}on {{ date }} at {{ time }}{% endblocktrans %}
            </small>
        </blockquote>
        {% if comment.author.pk == user.pk %}
        <div class="btn-toolbar"><div class="btn-group">
            <a class="btn btn-small"
               title="{% trans 'Update this comment' %}"
               href="{% url 'kdo-comment-update' comment.pk %}?next={{ request.get_full_path|urlencode }}">
                <i class="icon-pencil"></i>
            </a>
            <a class="btn btn-small"
               title="{% trans 'Delete this comment' %}"
               href="{% url 'kdo-comment-delete' comment.pk %}?next={{ request.get_full_path|urlencode }}">
                <i class="icon-trash"></i>
            </a>
        </div></div>
        {% endif %}
    </li>
{% endfor %}
</ul>
{% with present|comment_form:user as comment_form %}
<form action="{% url 'kdo-comment-create' object.pk %}" method="post">
    {% include 'snippets/field.html' with field=comment_form.text %}
    <button type="submit" class="btn">
        <i class="icon-comment"></i>
        {% trans 'Add a comment' %}
    </button>
    <input type="hidden" name="next" value="{{ request.get_full_path }}">
    {% csrf_token %}
</form>
{% endwith %}
{% endblock content %}

noyel/kdo/templates/kdo/present_list_for_giftee.html
{% extends 'kdo/present_list.html' %}

{% load i18n %}

{% block title %}{% blocktrans %}Gifts for {{ giftee }}{% endblocktrans %}{% endblock %}

{% block table_title %}
    {% blocktrans %}Gifts for {{ giftee }}{% endblocktrans %}
{% endblock %}

{% block create_present_url %}{% url 'kdo-present-create-for-giftee' giftee %}{% endblock %}

noyel/kdo/templates/kdo/present_update.html
{% extends 'kdo/present_create.html' %}

{% load i18n %}

{% block form_title %}
{% blocktrans with present=object.title %}Update the present "{{ present }}"{% endblocktrans %}
{% endblock %}